version: "3.3"
services:
    #==============================================>> eprocess
    eprocess:
        container_name: eprocess
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
        #     - ./vendor:/var/www/html/vendor
            - ./composer.json:/var/www/html/vendor/composer.json
            - ./storage:/var/www/html/storage
        ports:
            - "2009:80"
        environment:
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY: "base64:rN+E4wu2JTvHE8ZjM9ElfiHVcibR4r1BLNu9ULz0/wU="
            APP_DEBUG: true
            APP_URL: "http://localhost"
            LOG_CHANNEL: stack
            LOG_DEPRECATIONS_CHANNEL: null
            LOG_LEVEL: debug
            DB_CONNECTION: mysql
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: db_example
            DB_USERNAME: root
            DB_PASSWORD: 
            BROADCAST_DRIVER: log
            CACHE_DRIVER: file
            FILESYSTEM_DISK: local
            QUEUE_CONNECTION: sync
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120
            MEMCACHED_HOST: 127.0.0.1
            REDIS_HOST: 127.0.0.1
            REDIS_PASSWORD: null
            REDIS_PORT: 6379
            MAIL_MAILER: smtp
            MAIL_HOST: smtp.gmail.com
            MAIL_PORT: 587
            MAIL_USERNAME: "'your email'"
            MAIL_PASSWORD: "'azcjdlqxmkzyleho'"
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: '"hello@example.com"'
            MAIL_FROM_NAME: '"${APP_NAME}"'
            AWS_ACCESS_KEY_ID: 
            AWS_SECRET_ACCESS_KEY: 
            AWS_DEFAULT_REGION: us-east-1
            AWS_BUCKET: 
            AWS_USE_PATH_STYLE_ENDPOINT: false
            PUSHER_APP_ID: 
            PUSHER_APP_KEY: 
            PUSHER_APP_SECRET: 
            PUSHER_HOST: 
            PUSHER_PORT: 443
            PUSHER_SCHEME: https
            PUSHER_APP_CLUSTER: mt1
            VITE_PUSHER_APP_KEY: '"${PUSHER_APP_KEY}"'
            VITE_PUSHER_HOST: '"${PUSHER_HOST}"'
            VITE_PUSHER_PORT: '"${PUSHER_PORT}"'
            VITE_PUSHER_SCHEME: '"${PUSHER_SCHEME}"'
            VITE_PUSHER_APP_CLUSTER: '"${PUSHER_APP_CLUSTER}"'
        networks:
            - eprocess
networks:
    eprocess:
